apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: shell
  name: shell
spec:
  replicas: 1
  selector:
    matchLabels:
      run: shell
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: shell
    spec:
      containers:
      - image: jgreat/shell
        name: shell
        resources: {}
status: {}
